### ISSUE TITLE
Issue to welcome developers

### ISSUE THREAD

**Issue by arvchristos** [arvchristos/lo-page-numbering#1]
This issue serves as a starting point for developers during Hacktoberfest 2018.  

All issues tagged with the `Hacktoberfest` label are suitable for new contributors.

Check the contribution [guide](https://github.com/arvchristos/lo-page-numbering/blob/master/CONTRIBUTING.md) to get started.
For any further info as well as suggestions and discussion, please use the dedicated repository [IRC channel](https://riot.im/app/#/room/!pywEKwnnGVkNrbMljv:matrix.org) and/or the issue tracker. 

Stay tuned !

**Comment by gahan9** [comment]
by starting, what needs to be done?

**Comment by sudonotpseudo** [comment]
echoing @gahan9 what assistance seems to be needed?

**Comment by gahan9** [comment]
@sudonotpseudo "This issue serves as a starting point for developers" what this supposed to mean??

**Comment by sudonotpseudo** [comment]
@gahan9 I have about as much idea as you, which is none at all.  I too am interested in this project.

**Comment by arvchristos** [comment]
Hello to all and thanks for the willingness to help. I will soon include a starting guide as well as specific goals to be achieved. This serves more as a probe for contributor interest.

**Comment by arvchristos** [comment]
I suggest you join the repository [IRC channel](https://riot.im/app/#/room/!pywEKwnnGVkNrbMljv:matrix.org) for discussion about open issues as well as further enhancements and check this issue for updates.
