### ISSUE TITLE
Implement python script to create new .oxt file

### ISSUE THREAD

**Issue by arvchristos** [arvchristos/lo-page-numbering#15]
This is a beginner issue:

After developing a new version, the different files have to be packed in an `.oxt` file. Such an extension is essentially a `.zip` file with altered extension. To day this is done manually thus an simple automation trick would be really helpful.
 
This script should take all the files from /LibreOffice/python/oxt_metadata/ directory and zip them with the `.oxt` extension. The destination folder should be the `LibreOffice/versions/{ver_num}`.

For example, the upcoming 0.0.3 version should be saved in `LibreOffice/versions/0_0_3`

The version number should be passed as an argument.

Documentation for this script should be short and descriptive.

**Comment by felipemfp** [comment]
I'd like to take this, @arvchristos

**Comment by arvchristos** [comment]
@felipemfp 
I'd be more than happy if you did!
