### ISSUE TITLE
Transfer wiki pages  from gitlab repository on description to github

### ISSUE THREAD

**Issue by arvchristos** [arvchristos/lo-page-numbering#18]
This is a beginner task. 
Currently there is no standard way to mirror wiki pages across gitlab and github. For a beginner, simple creation of wiki pages would be a great start to git and github.

I suggest using the terminal cli to create the wiki pages and clone the wiki repository. 
Pages already exist [here](https://gitlab.com/lo_extensions/lo-page-numbering/wikis/home)

**Comment by Vinetos** [comment]
I'm on it 😄

**Comment by Vinetos** [comment]
You have to know that we can't make pull requests on wiki pages (officially).
To make it work, you should create a new repository with only the wiki and sync it to this project.

See: https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

**Comment by arvchristos** [comment]
You can create a wiki directory on the root of this repository. I will transfer the markdown files as soon as they are ready

**Comment by Vinetos** [comment]
There you go 😉

**Comment by HelenKing029** [comment]
I wouldn't mind giving this a try! I haven't done anything with Wiki pages and new to contributing so this would be a fun task!

**Comment by arvchristos** [comment]
@HelenKing029 sorry for the late response, I had closed the issue before seeing your comment. The pages have already been transferred. However, do not get disappointed and continue seeking for ways to contribute. I will be happy to get help and feedback from you.
