### ISSUE TITLE
Call for translators

### ISSUE THREAD

**Issue by arvchristos** [arvchristos/lo-page-numbering#22]
The extension includes a number of translatable strings in many aspects such as the user interface or the help pages. 

Translations are based on gettext .po files and currently the following are implemented:

- English en
- Greek el
- Italian it

More locales would help the extension become standard.

Consult the contribution guideline for more info.

 Please contact here if you are interested in translating any part of the extension.

**Comment by muelletr** [comment]
Hello, I can do the translation to german.

**Comment by arvchristos** [comment]
Hello @muelletr . I am glad to help you throughout this process. Please follow the steps as defined in the following readme [link](https://gitlab.com/lo_extensions/l10n-utility/blob/master/README.md) and reach out here for any problem. 

Before starting, you have to fork this repository and the l10n utility one located [here](https://github.com/arvchristos/l10n-utility)

**Comment by arvchristos** [comment]
> Hello, I can do the translation to german.

please check #25 for discussion and further info

**Comment by muelletr** [comment]
@arvchristos I think I don't understand the README correctly.
In which directory I should execute the command from the README?
`python2.7 l10next.py ./PageNumberingAddonPython-0.0.1.oxt it`
I think it should be executed in lo-page-numbering/LibreOffice/python/build_files where the PageNumberingAddonPython-0.0.1.oxt file is located. 

After I did that I chose option 1 to edit the UI and added the translation. I stored the changes and on the command line I went back and chose option 5 to compile the localized extension.

If I do that there are many new files:
 
![translation-de](https://user-images.githubusercontent.com/14543255/46580440-28170c80-ca25-11e8-8c00-fcddb2bf3020.png)

**Comment by arvchristos** [comment]
@muelletr 
The new locale files are saved in separate folders in the same directory as the l10next.py.
From the lo-page-numbering repository, you only need the .oxt from LibreOffice/versions/0_0_2
This is the argument for the l10next.py.
The new files that are generated should be pushed in the locales directory of the root of this repository. They are needed for me to include the new locale in the next version.

**Comment by muelletr** [comment]
Should I only push the two files at `de/LC_MESSAGES` to `LibreOffice/python/oxt_metadata/0_0_2/python/locales`?

**Comment by arvchristos** [comment]
@muelletr you should push all files/directories generated by the l10next.py to REPOSITORY/locales/de and let me after testing, do the integration.

**Comment by gersongams** [comment]
Hi, Don't you need a spanish translator?

**Comment by robotenique** [comment]
Hello, I can do the translation to portuguese (brazilian >:D)

**Comment by arvchristos** [comment]
@robotenique Please follow the contribution guideline of the root directory and contact me for any question. Thank you!

**Comment by PrathameshPatole** [comment]
Hello I can do the translation in Hindi

**Comment by PrathameshPatole** [comment]
I am still a beginner could you help me as to how to get started

**Comment by Feyn-Man** [comment]
Hi all! I could work on the italian translation but I'm unable to install all the packages needed to run l10n utility. For example when I run `pip install os` I get this:
`Could not find a version that satisfies the requirement os (from versions: )
No matching distribution found for os`
and the same for the other packages needed.
Does anyone have faced this error or have an idea on how to solve it?

**Comment by arvchristos** [comment]
@Feyn-Man Thank you. However the Italian localization is already completed as stated in the CHANGELOG.md

**Comment by Feyn-Man** [comment]
Uh, ok! I didn't see it!

**Comment by rodrinrj** [comment]
Hello! I can help with the Spanish translation. Please respond if needed!

**Comment by arvchristos** [comment]
@rodrigonp thank you for the interest. I am afraid the Spanish translation is already completed. However, you could install the latest version (0.0.3) from this repo and test it for any typo if you are still willing to help.

**Comment by Dratui** [comment]
Hello ! If you want, I'm interested in translating in French. Any tip to begin ? What's the most important file to translate ?
