### ISSUE TITLE
Norwegian translation

### ISSUE THREAD

**Issue by arvchristos** [arvchristos/lo-page-numbering#24]
- [X] UI
- [x] License (will use the English one till Norwegian translation is found )
- [x] Extension Description
- [ ] Help pages

**Comment by MasterOfTheTiger** [comment]
I cannot find any translation of the GPL License into Norwegian anywhere.

**Comment by arvchristos** [comment]
@MasterOfTheTiger Unfortunately, I couldn't either. However, the English one should fit and license translation is not a high priority.

**Comment by Ondkloss** [comment]
@arvchristos if translating help pages I'm kind of wondering what words/phrases are "reserved" (should not be edited). Am I correct in assuming "Page Numbering" will always be the title under the "Insert"-menu? If so, I guess that should remain in the help files as well? Other than that it seems to me all other strings are OK with being translated. For example, the word "addon" (also seen as "add-on") would seem to appear in a context where it makes sense to translate it. Comments?

**Comment by arvchristos** [comment]
I would recommend translating all strings except the Page numbering one as you already stated. Those are things that should be mentioned in the translator' s documentation. Thank you for the feedback. 

P.s. please commit your changes to a separate directory in lolales/no and avoid directly editing those of a version.

**Comment by Ondkloss** [comment]
@arvchristos your last point interests me. Could you specify which `locales/no` you are talking about? I think [the guide](https://gitlab.com/lo_extensions/lo-page-numbering/wikis/Localization-tutorial) includes an outdated path. It specified:

    cd ./lo-page-numbering/LibreOffice/python/build_files/python/

For the LibreOffice folder I only find version-related paths. Do you mean under the OpenOffice folder? If so I find the following paths:

    lo-page-numbering/OpenOffice/python/build_files/python/locales
    lo-page-numbering/OpenOffice/python/oxt_metadata/help

**Comment by arvchristos** [comment]
The locales directory of the root of this repository. I try to integrate the changes myself before changing version files

**Comment by Ondkloss** [comment]
@arvchristos I was thinking of wrapping this up using your l10n-utility, but what location for the PageNumberingAddon.oxt are you supposed to use? Under /LibreOffice/python/build_files there's only a version called PageNumberingAddonPython-0.0.1.oxt. I want to be sure I'm using the newest version before going through the sections and adding it to the root locales directory.

**Comment by arvchristos** [comment]
If I understand, you refer to the location of the parameter passed to the l10next utility. I suggest you use the latest stable version , thus please use the PageNunberingAddon.oxt on the LibreOffice/versions/0.0.2 directory

**Comment by Ondkloss** [comment]
@arvchristos I've made an attempt using the l10n-utility, if you could take a look at it.

**Comment by arvchristos** [comment]
@Ondkloss Could you please submit a pull request with your implementation for me to review it? 
Thank you

**Comment by arvchristos** [comment]
@Ondkloss Sorry for the late response, I will review it ASAP. Thank you for the effort
