### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by arvchristos** [arvchristos/lo-page-numbering#25]
- [x] UI
- [x] License
- [x] Extension Description
- [x] Help pages

**Comment by MasterOfTheTiger** [comment]
http://www.gnu.de/documents/gpl-3.0.de.html for license.

**Comment by arvchristos** [comment]
> http://www.gnu.de/documents/gpl-3.0.de.html for license.

Would you like to contribute the license text to locales/de directory?

**Comment by muelletr** [comment]
When I execute the translation for the help pages from the command prompt I get an error 

> can't open file ./PageNumberingAddon.oxt_help_pages_de/pages/base.po

**Comment by arvchristos** [comment]
@muelletr Have you installed the dependencies of l10n-utility as stated in the repo?

**Comment by MasterOfTheTiger** [comment]
> Would you like to contribute the license text to locales/de directory?

There should be a disclaimer that states that the German translation does not represent the actual licensing requirements, but only helps Germans that do not understand English to understand the GPL license. You do not want people to misunderstand that. 

Oh wait, there is a disclaimer there already. I will submit a pull request with the license if that is okay with you (I do not actually know German).

**Comment by arvchristos** [comment]
@MasterOfTheTiger sure, we could require each translation to include such a disclaimer.

**Comment by muelletr** [comment]
@arvchristos yes, I installed all the packages mentioned in the readme

**Comment by arvchristos** [comment]
@muelletr Does this file exist in your directory?

**Comment by muelletr** [comment]
@arvchristos the directory for the german version is empty

**Comment by arvchristos** [comment]
you should execute the l10next.py utility with the files generated by this. After the first execution you ended with two additional directories. Those should exist for the next execution of l10next.py. 

I try to understand where the problem is so forgive anything that seems irrelevant

**Comment by muelletr** [comment]
I tried it again, the directories are created but they are empty

**Comment by arvchristos** [comment]
Have you installed itstool?

**Comment by muelletr** [comment]
Yes, I did

**Comment by arvchristos** [comment]
Are you running on windows platform?

**Comment by muelletr** [comment]
No, on Ubuntu

**Comment by arvchristos** [comment]
Please copy l10next.py and rules.its to locales/de and then rerun the script

**Comment by muelletr** [comment]
Now it works! Thank you

**Comment by MasterOfTheTiger** [comment]
@arvchristos Where should the license file be? And should the file name simply be LICENSE?

**Comment by arvchristos** [comment]
@MasterOfTheTiger  The license file should be included in:
`locales/de/PageNumberingAddon.oxt_extracted/Legal/`

Please follow the naming scheme seen in other files on the same directory.

**Comment by MasterOfTheTiger** [comment]
@arvchristos So license-de.txt?

**Comment by MasterOfTheTiger** [comment]
@arvchristos So licese-de.txt? I will submit a pull request and see if that is what you want.

**Comment by arvchristos** [comment]
Yes !
