### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by arvchristos** [arvchristos/lo-page-numbering#38]
- [X] UI
- [ ] License (will use the English one till Norwegian translation is found )
- [ ] Extension Description
- [ ] Help pages

Please consult the CONTRIBUTING.md guideline before contributing.

**Comment by asiedubrempong** [comment]
Can someone explain the issue to me? 
Would be glad to work on it.

**Comment by arvchristos** [comment]
@asiedubrempong Please check the wiki regarding the localization process. For any questions ping  through the IRC channel. Thanks in advance
