### ISSUE TITLE
Beautify code for extension

### ISSUE THREAD

**Issue by arvchristos** [arvchristos/lo-page-numbering#4]
This is a beginners task. Pep 8 for [main.py](https://github.com/arvchristos/lo-page-numbering/blob/master/LibreOffice/python/oxt_metadata/0_0_2/python/main.py) as well as beautification of different files, and especially .pot translation templates is needed.

**Comment by io-ma** [comment]
Dibs on this one :smile:

**Comment by arvchristos** [comment]
Welcome @io-ma !

**Comment by io-ma** [comment]
Cheers!

**Comment by ghost** [comment]
I'll work on it, too.

**Comment by arvchristos** [comment]
Welcome too @midnio !

**Comment by ghost** [comment]
#7

**Comment by io-ma** [comment]
https://github.com/arvchristos/lo-page-numbering/pull/8

**Comment by arvchristos** [comment]
Thank you both @io-ma and @midnio for the contributions.

I consider this issue resolved. Hope to see more of you!
