### ISSUE TITLE
Compose wiki pages

### ISSUE THREAD

**Issue by arvchristos** [arvchristos/lo-page-numbering#5]
This is a beginner issue.

Page numbering addon would be significantly improved if users with experience over LibreOffice application development helped in the writing of helpful wiki pages regarding Python extension development for LO/OO.

Any ideas as well as suggestions would be highly appreciated.

**Comment by io-ma** [comment]
@arvchristos:
I am working on it.
Of course I will add more to it, just wanted to check:
Is this similar to what you had in mind? Pages could be added later, of course.
https://github.com/io-ma/lo-page-numbering/wiki/Style-guide-for-the-Libre-Office-Page-Numbering-addon

**Comment by arvchristos** [comment]
Yes , this seems great !!

**Comment by io-ma** [comment]
https://github.com/arvchristos/lo-page-numbering/issues/9#issuecomment-426618528

**Comment by io-ma** [comment]
https://github.com/arvchristos/lo-page-numbering/pull/21

**Comment by io-ma** [comment]
So you need more pages to the Wiki? Let's do this!

**Comment by arvchristos** [comment]
@io-ma That would be great. What topics do you think you should cover. Are you familiar with LibreOffice extension coding?

**Comment by io-ma** [comment]
I am a Linux user and it would be great if I could help with documentation, but I am not familiar with LibreOffice extension coding. Just found your repo on Github , searching for Python OS projects I could contribute to. But I am ok with writing stuff, so I don't know what I could cover :-D

**Comment by arvchristos** [comment]
Sorry for the late response. As of now, I cannot think of any wiki page that needs to be written, taking into consideration the small size of such an extension. The only topic that needs to be documented is the localization process that is far from complete. As soon as this is completed I will state the exact wiki pages that need to be compiled. 

Thanks for the help !

**Comment by arvchristos** [comment]
@io-ma  I have updated the wiki pages. If you have anything to correct I would be happy to accept a contribution for you. As for the naming conventions, we use the [UpperCamelCase](http://wiki.c2.com/?UpperCamelCase) one.

**Comment by io-ma** [comment]
Cool, will do this tomorrow!
