### ISSUE TITLE
Construct python formatting wiki page 

### ISSUE THREAD

**Issue by arvchristos** [arvchristos/lo-page-numbering#9]
This is a beginner task:
A great contribution to the addon would be the creation of wiki page with links to proper Python formatting principles to be followed along this project. I imagine this as a .md file with a list of steps and documentation for proper contributing.

**Comment by arvchristos** [comment]
@midnio @io-ma This would be an easy task for you that already contributed to the main.py formatting

**Comment by io-ma** [comment]
Will do tomorrow, good idea.

**Comment by io-ma** [comment]
https://github.com/arvchristos/lo-page-numbering/issues/5#issuecomment-426553907

**Comment by io-ma** [comment]
Ready on my part, you just need to add the naming conventions you use to the subcategories. 
If you tell me which they are, I could add them myself. 
Would you make a new repo for the wiki so I can fork it and push it? 
I have no preference, really it's just a pull request and I have a whole month ahead to make others.
You could simply clone it from me and add a wiki page directly to your existing repo.
https://github.com/io-ma/lo-page-numbering/wiki/Style-guide-for-the-Libre-Office-Page-Numbering-addon

**Comment by arvchristos** [comment]
I would suggest you create a directory in the root of the repository woth the markdown files till I decide what to do with the wiki. This is what is already done by a different contributor. 

Thanks a lot for the contribution !

**Comment by io-ma** [comment]
https://github.com/arvchristos/lo-page-numbering/pull/21

**Comment by arvchristos** [comment]
Thank you @io-ma

**Comment by io-ma** [comment]
Hey, if you tell me what the naming style is I can complete that part too.
